#!/bin/bash
echo "Setting up iTerm2 to use synced folder"
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/.punctuation/iterm2"
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true
