#!/bin/bash

url="$1"
output="$2"
seek="$3"
trim="$4"


m3u8=$(livestreamer -j "$url" | jq -r ".streams.best.url")

ffmpeg ${seek:+-ss} $seek -i "$m3u8" ${trim:+-t} $trim -c copy -bsf:a aac_adtstoasc "$output"
